spring: 
  profiles: 
    active: 
    - dev

---
server: 
  port: 8761			 
spring: 
  profiles: dev			#开发环境
  application: 
    name: microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka8761.com	   #eureka集群中名字
  client: 
    register-with-eureka: false    #自己不被注册进eureka
    fetch-registry: false          #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka8761.com:8761/eureka/
      
---
server: 
  port: 8761			

spring: 
  profiles: test			#测试环境
  application: 
    name: microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka8761.com	   #eureka集群中名字
  client: 
    register-with-eureka: false    #自己不被注册进eureka
    fetch-registry: false          #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka8761.com:8761/eureka/